import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Link from "next/link";

export interface User {
	id: string;
	title: string;
	url: string;
}

function List({ users }: { users: User[] }) {
	return (
		<>
			<ul>
				{users.map((user) => (
					<li key={user.id}>
						<Link href={`/users/${user.id}`} passHref>
							<a>{user.id}</a>
						</Link>
					</li>
				))}
			</ul>
		</>
	);
}

const Home: NextPage = () => {
	const [loader, setLoader] = useState<boolean>(true);
	const [data, setData] = useState<User[]>([]);

	const getUsers = async () => {
		const req = await fetch("https://jsonplaceholder.typicode.com/photos");
		const users = await req.json();
		setLoader(false);
		setData(users);
	};
	useEffect(() => {
		getUsers();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Fetching Data For CSR</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1>Fetching data for csr</h1>
			{loader && <div>Loading Uers ...</div>}
			{data.length > 0 && <List users={data} />}
		</div>
	);
};

export default Home;
