import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../component/Navbar";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Link Navigation</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>This Is Home Page</h1>
			<Navbar></Navbar>
		</div>
	);
};

export default Home;
